name: API Tests with Allure and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Fix DNS resolution for GitHub runner
        run: echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null

      - name: Set up Maven Central mirror fallback
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <mirror>
                <id>central</id>
                <mirrorOf>central</mirrorOf>
                <url>https://repo1.maven.org/maven2</url>
              </mirror>
            </mirrors>
          </settings>' > ~/.m2/settings.xml

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Docker login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/ahmed-shaaban1/api-automation-framework-for-fakerestapi:latest .

      - name: Run API Tests with Maven
        run: mvn clean test

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -fLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip -q allure.zip -d allure
          sudo mv allure/allure-2.27.0 /opt/allure
          sudo ln -sf /opt/allure/bin/allure /usr/bin/allure
          allure --version
